=== joshepDAM1986/VSCode/Lenguaje  de Marcas/XML/_battala_xml/productos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="cafeteria">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="productos" type="productosType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="productosType">
    <xs:sequence>
      <xs:element name="producto" maxOccurs="unbounded" type="productoType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="productoType">
    <xs:sequence>
      <xs:element name="nombre" type="nombreType"/>
      <xs:element name="descripcion" type="descripcionType"/>
      <xs:element name="categoria" type="categoriaType"/>
      <xs:element name="precio" type="precioType"/>
      <xs:element name="fecha" type="fechaType"/>
      <xs:element name="stock" type="stockType"/>
      <xs:element name="alergenos" type="alergenosType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="nombreType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-záéíóúüñÑ\s]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="descripcionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Za-záéíóúüÑñ0-9\s]+"/>
      <xs:maxLength value="50"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="categoriaType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Pastelería"/>
      <xs:enumeration value="Cafetería"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="precioType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0.01"/>
      <xs:maxInclusive value="250.00"/>
      <xs:fractionDigits value="2"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fechaType">
    <xs:annotation>
      <xs:documentation>Fecha en formato yyyy-mm-dd en el rango desde 2000 hasta 2023.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="((20\d{2}|19\d{2}|200\d|201[0-9]|202[0-3]))-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="stockType">
    <xs:restriction base="xs:integer">
      <xs:minExclusive value="00"/>
      <xs:maxInclusive value="200"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="alergenosEnumType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Gluten"/>
      <xs:enumeration value="Crustáceos"/>
      <xs:enumeration value="Huevos"/>
      <xs:enumeration value="Pescados"/>
      <xs:enumeration value="Cacahuetes"/>
      <xs:enumeration value="Lácteos"/>
      <xs:enumeration value="Cáscara"/>
      <xs:enumeration value="Sésamo"/>
      <xs:enumeration value="Sulfitos"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="alergenosType">
    <xs:list itemType="alergenosEnumType"/>
  </xs:simpleType>
</xs:schema>

=== joshepDAM1986/VSCode/Lenguaje  de Marcas/XML/_battala_xml/productos.xml
<?xml version="1.0" encoding="UTF-8"?>
<cafeteria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="productos.xsd">
  <productos>
    <producto>
      <nombre>Cafe Americano</nombre>
      <descripcion>Café negro y sin azúcar</descripcion>
      <categoria>Cafetería</categoria>
      <precio>2.50</precio>
      <fecha>2000-01-01</fecha>
      <stock>20</stock>
      <alergenos>Huevos Sulfitos</alergenos>
    </producto>
    <producto>
      <nombre>Capuchino</nombre>
      <descripcion>Espresso  con leche vaporizada y espuma de leche</descripcion>
      <categoria>Cafetería</categoria>
      <precio>3.50</precio>
      <fecha>2000-02-02</fecha>
      <stock>20</stock>
      <alergenos>Huevos</alergenos>
    </producto>
    <producto>
      <nombre>Tarta Manzana</nombre>
      <descripcion>Tarta con relleno de manzana y crujiente de canela</descripcion>
      <categoria>Pastelería</categoria>
      <precio>100</precio>
      <fecha>2002-03-03</fecha>
      <stock>200</stock>
      <alergenos>Huevos</alergenos>
    </producto>
    <producto>
      <nombre>Croissant</nombre>
      <descripcion>Croissant de mantequilla recién horneado</descripcion>
      <categoria>Pastelería</categoria>
      <precio>0.01</precio>
      <fecha>2003-04-04</fecha>
      <stock>20</stock>
      <alergenos>Huevos</alergenos>
    </producto>
    <producto>
      <nombre>Latte Macchiato</nombre>
      <descripcion>Leche caliente con una capa de espresso</descripcion>
      <categoria>Cafetería</categoria>
      <precio>3.20</precio>
      <fecha>2004-05-05</fecha>
      <stock>20</stock>
      <alergenos>Huevos</alergenos>
    </producto>
    <producto>
      <nombre>Muffin Arándanos</nombre>
      <descripcion>Muffin esponjoso con arándanos frescos</descripcion>
      <categoria>Pastelería</categoria>
      <precio>2.80</precio>
      <fecha>2005-06-06</fecha>
      <stock>20</stock>
      <alergenos>Huevos</alergenos>
    </producto>
    <producto>
      <nombre>Espresso</nombre>
      <descripcion>Pequeño y fuerte café</descripcion>
      <categoria>Cafetería</categoria>
      <precio>2.00</precio>
      <fecha>2006-07-07</fecha>
      <stock>20</stock>
      <alergenos>Huevos</alergenos>
    </producto>
    <producto>
      <nombre>Croissant Chocolate</nombre>
      <descripcion>Croissant relleno de chocolate</descripcion>
      <categoria>Pastelería</categoria>
      <precio>2.00</precio>
      <fecha>2007-08-08</fecha>
      <stock>20</stock>
      <alergenos>Huevos</alergenos>
    </producto>
    <producto>
      <nombre>Cappuccino</nombre>
      <descripcion>Espresso con leche vaporizada y espuma de leche</descripcion>
      <categoria>Cafetería</categoria>
      <precio>3.50</precio>
      <fecha>2008-09-09</fecha>
      <stock>20</stock>
      <alergenos>Huevos</alergenos>
    </producto>
    <producto>
      <nombre>Tarta Chocolate</nombre>
      <descripcion>Tarta decorada con virutas de chocolate</descripcion>
      <categoria>Pastelería</categoria>
      <precio>4.20</precio>
      <fecha>2009-10-10</fecha>
      <stock>20</stock>
      <alergenos>Huevos</alergenos>
    </producto>
  </productos>
</cafeteria>
