=== joshepDAM1986/VSCode/Lenguaje  de Marcas/XML/_ejercicio_3_pag_195.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" 
xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="calificaciones">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="alumno" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="alumno">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="datos"/>
                <xs:element ref="materia"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="datos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="apellidos" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="materia">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="oace"/>
                <xs:element ref="eee"/>
                <xs:element ref="xml"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="oace">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cuestionario" type="xs:integer"/>
                <xs:element name="tareas" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="eee">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cuestionario" type="xs:integer"/>
                <xs:element name="tareas" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="xml">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cuestionario" type="xs:integer"/>
                <xs:element name="tareas" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
     
</xs:schema>

=== joshepDAM1986/VSCode/Lenguaje  de Marcas/XML/_ejercicio_3_pag_195_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<calificaciones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="_ejercicio_3_pag_195.xsd">
    <alumno>
        <datos>
            <nombre>Felipe</nombre>
            <apellidos>Pascal</apellidos>
        </datos>
        <materia>
            <oace>
                <cuestionario>4</cuestionario>
                <tareas>8</tareas>
            </oace>
            <eee>
                <cuestionario>7</cuestionario>
                <tareas>6</tareas>
            </eee>
            <xml>
                <cuestionario>8</cuestionario>
                <tareas>6</tareas>
            </xml>
        </materia>
    </alumno>
    <alumno>
        <datos>
            <nombre>María</nombre>
            <apellidos>García</apellidos>
        </datos>
        <materia>
            <oace>
                <cuestionario>9</cuestionario>
                <tareas>2</tareas>
            </oace>
            <eee>
                <cuestionario>9</cuestionario>
                <tareas>6</tareas>
            </eee>
            <xml>
                <cuestionario>7</cuestionario>
                <tareas>7</tareas>
            </xml>
        </materia>
    </alumno>
</calificaciones>
