<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BDusuarios [

    <!ELEMENT BDusuarios (usuario)+>
    <!ELEMENT usuario (nombre,email,fechaNac,permisos,suceso)>

    <!ATTLIST usuario
clave CDATA #REQUIRED  
dni CDATA #IMPLIED 
tipo (usuario|administrador) #IMPLIED>

    <!ATTLIST permisos
r (true|false) #REQUIRED 
x (true|false) #REQUIRED 
w (true|false) #REQUIRED>

    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT fechaNac (#PCDATA)>
    <!ELEMENT permisos EMPTY>
    <!ELEMENT suceso (#PCDATA)>

    <!ENTITY web "http://atlantidad.es">
    <!ENTITY cliente "Se informa de que el ususario ha accedido al">


]>

<BDusuarios>
    <usuario clave="01" dni="12345678A" tipo="usuario">
        <nombre>Ataulfo G.Pascual</nombre>
        <email>user1@librolm.com</email>
        <fechaNac>16/02/90</fechaNac>
        <permisos r="true" x="true" w="false"></permisos>
        <suceso>&cliente; contenido de &web;
            para consultar el libro X
        </suceso>
    </usuario>
    <usuario clave="02" dni="87654321B" tipo="administrador">
        <nombre>Francisco J.Garcia</nombre>
        <email>user2@librolm.com</email>
        <fechaNac></fechaNac>
        <permisos r="true" x="true" w="false"></permisos>
        <suceso>&cliente; contenido de &web;
            para consultar el libro H
        </suceso>
    </usuario>
</BDusuarios>